### PR TITLE
Release 8.8.0 -- add ca_cert_identifier to rds module

### PR DESCRIPTION
**Pull request by briskt**
### Added
- In `rds/mariadb` module, added an optional variable `ca_cert_identifier` to specify the CA Certificate for the RDS instance.
- In `rds/mariadb` module, added an optional variable `apply_immediately` to force any changes to be applied immediately rather that at the next maintenance window.

### CODE REVIEW

**Comment by BarnumD** [comment]
Should `rds-ca-rsa2048-g1` be the default so that `ca_cert_identifier` is not a required field?
`rds-ca-rsa4096-g1` is also available for additional security (with more overhead) and `rds-ca-ecc384-g1` using an elliptic curve algorithm may provide better security, but less compatibility with older apps.

**Comment by briskt** [comment]
> Should `rds-ca-rsa2048-g1` be the default so that `ca_cert_identifier` is not a required field? `rds-ca-rsa4096-g1` is also available for additional security (with more overhead) and `rds-ca-ecc384-g1` using an elliptic curve algorithm may provide better security, but less compatibility with older apps.

I set `null` as the default so it's not a required variable and not a breaking change. We can set `rds-ca-rsa2048-g1` as the default for the IdP since it's not a public repo.

**Comment by BarnumD** [comment]
So what is the behavior when it's `null`?  Terraform detects no changes needed?

**Comment by briskt** [comment]
It is the same as if no value is provided, so the provider sets the default value.

**Review by forevermatt — APPROVED** [review]

**Pull request merged**
