### PR TITLE
RDS: Add copy_tags_to_snapshot functionality.

### PR DESCRIPTION
**Pull request by BarnumD**

### CODE REVIEW

**Comment by BarnumD** [comment]
Would like to improve tag ubiquity with this change to add tags to rds snapshots. @fillup @Schparky

**Review by briskt — APPROVED** [review]

**Comment by BarnumD** [comment]
By the way, if you always (or usually) wanted rds to copy tags to the snapshots, we could update the default here to `true`.  The default for the aws_db_instance resource is `false`, however.

**Review by fillup — APPROVED** [review]

**Comment by fillup** [comment]
I do like the idea of defaulting to true. @BarnumD do you want to make that the default here and then we'll merge?

**Comment by BarnumD** [comment]
Changed to `true`.  @fillup

**Pull request merged**
