### PR TITLE
Update default CA Cert to RSA2048-g1

### PR DESCRIPTION
**Pull request by BarnumD**
The rds-ca-2019 is being retired in August 2024.

### CODE REVIEW

**Comment by BarnumD** [comment]
I tested this and it applied successfully, but then I noticed it didn't actually change the CA Authority.  It may be waiting until the next maintenance window, but so far I don't see evidence of that.

**Comment by BarnumD** [comment]
The issue I mentioned is documented here
https://github.com/hashicorp/terraform-provider-aws/issues/33546

I had to add `apply_immediately` for the change to take effect.  This appears to cause the action of terraform to apply immediately.  I was wondering if it would also change the default behavior of the GUI, but in the GUI, after the change was made, the default option when modifying the database is still 'Apply during the next scheduled maintenance window'.

Let me know if you'd rather leave out the `apply_immediately`.  It will mean that the CA change won't get changed automatically or during a maintenance window (due to the bug), but it could be applied manually in the user interface.

**Comment by briskt** [comment]
> The issue I mentioned is documented here [hashicorp/terraform-provider-aws#33546](https://github.com/hashicorp/terraform-provider-aws/issues/33546)
> 
> I had to add `apply_immediately` for the change to take effect. This appears to cause the action of terraform to apply immediately. I was wondering if it would also change the default behavior of the GUI, but in the GUI, after the change was made, the default option when modifying the database is still 'Apply during the next scheduled maintenance window'.
> 
> Let me know if you'd rather leave out the `apply_immediately`. It will mean that the CA change won't get changed automatically or during a maintenance window (due to the bug), but it could be applied manually in the user interface.

Thank you for investigating and troubleshooting, @BarnumD! It's concerning to me that there's an unresolved bug related to this. Also the `apply_immediately` can be problematic ("using apply_immediately can result in a brief downtime as the server reboots") or at least not well understood at this time. I'm more inclined to apply the cert manually or wait until the bug has been fixed. Since we don't currently use SSL or TLS on the database connection, it's not an urgent matter.

**Comment by BarnumD** [comment]
I have removed apply_immediately since you have some concern about it.
I think we could still merge this even with the bug.  It will 1. inform us a change is needed and 2. allow newly created databases to hopefully get the new recommended certificate authority.

**Comment by briskt** [comment]
> I have removed apply_immediately since you have some concern about it. I think we could still merge this even with the bug. It will 1. inform us a change is needed and 2. allow newly created databases to hopefully get the new recommended certificate authority.

Based on the most recent three messages in the linked issue, it sounds to me like the Terraform state would be updated without updating the AWS infrastructure. If I interpret that correctly, later updates after the bug is fixed would do nothing, leaving the old certificate in place indefinitely. If you want to move forward with this before the bug is fixed, I would like the default value of `ca_cert_identifier` to be null. Hopefully that would prevent any changes unless a value is explicitly provided.

**Comment by BarnumD** [comment]
I'm not sure what you mean.  Currently terraform asks for it to be updated each time it runs, even if applied.  That indicates to me that the state is not in some limbo mode, but recognizes a change is still needed.

**Comment by briskt** [comment]
> I'm not sure what you mean. Currently terraform asks for it to be updated each time it runs, even if applied. That indicates to me that the state is not in some limbo mode, but recognizes a change is still needed.

OK, that's good news. Does that mean that until the bug is fixed, every time a plan is created, it will show a change? That's not serious, but does seem a little tedious.

**Comment by BarnumD** [comment]
Yes, it will show a change is necessary every time.  Until you manually update the certificate authority to the new recommended one in the RDS console.  Then terraform is happy and no change is needed.
Annoying, but a good reminder, as the old authority expires in August.

**Comment by briskt** [comment]
> Yes, it will show a change is necessary every time. Until you manually update the certificate authority to the new recommended one in the RDS console. Then terraform is happy and no change is needed. Annoying, but a good reminder, as the old authority expires in August.

Good point. Let's give it a try.

**Pull request merged**
